import streamlit as st


def show_terms():
    """Display the Terms of Service page"""
    st.markdown("""
<style>
.main {
padding: 2rem;
max-width: 900px;
margin: 0 auto;
}
.hero-section {
background: linear-gradient(135deg, #2B3447 0%, #667eea 100%);
color: white;
padding: 2rem;
border-radius: 10px;
margin-bottom: 2rem;
text-align: center;
}
.section {
margin-bottom: 2rem;
}
.section h2 {
color: #667eea;
margin-bottom: 1rem;
}
.warning-box {
background: #fff3cd;
border-left: 4px solid #ffc107;
padding: 1rem;
margin: 1rem 0;
border-radius: 4px;
}
</style>
""", unsafe_allow_html=True)

    # Hero
    st.markdown("""
<div class="hero-section">
<h1>📋 Terms of Service</h1>
<p>Last Updated: December 4, 2025</p>
</div>
    """, unsafe_allow_html=True)

    # Introduction
    st.markdown("""
<div class="section">
<h2>1. Agreement to Terms</h2>
<p>By accessing and using FinSim ("the Service"), you accept and agree to be bound by these 
Terms of Service ("Terms"). If you disagree with any part of these terms, you may not use the Service.</p>
        
<div class="warning-box">
<strong>⚠️ IMPORTANT:</strong> FinSim is an educational tool only. It is NOT financial advice. Always consult with qualified financial advisors, tax professionals, and attorneys before making financial decisions.
</div>
</div>
    """, unsafe_allow_html=True)

    # Definitions
    st.markdown("""
<div class="section">
<h2>2. Definitions</h2>
<ul>
<li><strong>"Service"</strong> refers to FinSim, including all features, content, and functionality</li>
<li><strong>"User," "you," "your"</strong> refers to the person accessing the Service</li>
<li><strong>"We," "us," "our"</strong> refers to FinSim and its operators</li>
<li><strong>"Content"</strong> refers to simulations, reports, data, and materials generated by the Service</li>
</ul>
</div>
    """, unsafe_allow_html=True)

    # Account Terms
    st.markdown("""
<div class="section">
<h2>3. Account Terms</h2>
        
<h3>3.1 Account Creation</h3>
<ul>
<li>You must be at least 18 years old to use this Service</li>
<li>You must provide accurate, complete information during registration</li>
<li>You are responsible for maintaining the security of your account and password</li>
<li>One account per person (no duplicate accounts)</li>
<li>You are responsible for all activity under your account</li>
<li>Account suspension/deactivation for violation of rate limits</li>
</ul>
        
<h3>3.2 Account Security</h3>
<ul>
<li>Choose a strong, unique password</li>
<li>Do not share your login credentials</li>
<li>Notify us immediately of any unauthorized access</li>
<li>We are not liable for losses due to stolen/compromised passwords</li>
</ul>
        
<h3>3.3 Account Termination</h3>
<p>We reserve the right to suspend or terminate accounts that:</p>
<ul>
<li>Violate these Terms</li>
<li>Engage in fraudulent or abusive behavior</li>
<li>Attempt to harm or exploit the Service</li>
<li>Remain inactive for more than 2 years</li>
</ul>
<p>You may delete your account at any time by contacting us.</p>
</div>
    """, unsafe_allow_html=True)

    # Use of Service
    st.markdown("""
<div class="section">
<h2>4. Acceptable Use</h2>
        
<h3>4.1 You MAY:</h3>
<ul>
<li>✅ Use the Service for personal financial planning</li>
<li>✅ Run simulations within rate limits (10/month for free users)</li>
<li>✅ Export your data in PDF/Excel format</li>
<li>✅ Share general insights from your simulations</li>
</ul>
        
<h3>4.2 You MAY NOT:</h3>
<ul>
<li>❌ Use the Service for commercial purposes without permission</li>
<li>❌ Attempt to reverse engineer, decompile, or hack the Service</li>
<li>❌ Circumvent rate limits or security measures</li>
<li>❌ Upload malicious code or viruses</li>
<li>❌ Engage in any systematic retrieval of data or other content from the Service to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us.</li>
<li>❌ Impersonate others or create fake accounts</li>
<li>❌ Resell or redistribute the Service</li>
<li>❌ Use the Service for illegal activities</li>
</ul>
</div>
    """, unsafe_allow_html=True)

    # Educational Disclaimer
    st.markdown("""
<div class="section">
<h2>5. Educational Tool - Not Financial Advice</h2>
        
<div class="warning-box">
<strong>⚠️ CRITICAL DISCLAIMER</strong>
</div>
        
<h3>5.1 What FinSim IS:</h3>
<ul>
<li>An educational tool for learning about financial projections</li>
<li>A calculator for exploring different scenarios</li>
<li>A way to visualize potential financial futures</li>
</ul>
        
<h3>5.2 What FinSim IS NOT:</h3>
<ul>
<li>❌ Financial advice or investment recommendations</li>
<li>❌ A substitute for professional financial planning</li>
<li>❌ A guarantee of future financial outcomes</li>
<li>❌ Tax, legal, or accounting advice</li>
</ul>
        
<h3>5.3 Limitations</h3>
<ul>
<li>Simulations are based on assumptions and historical data</li>
<li>Past market performance does not guarantee future results</li>
<li>Cannot account for all possible life events or economic scenarios</li>
<li>Tax implications are simplified or omitted</li>
<li>Currency conversions use approximate rates</li>
<li>Results are estimates only</li>
</ul>
        
<h3>5.4 Your Responsibility</h3>
<p><strong>You are solely responsible for:</strong></p>
<ul>
<li>All financial decisions you make</li>
<li>Consulting with qualified professionals (financial advisors, CPAs, attorneys)</li>
<li>Verifying all calculations and assumptions</li>
<li>Understanding the limitations of Monte Carlo simulations</li>
</ul>
</div>
    """, unsafe_allow_html=True)

    # Intellectual Property
    st.markdown("""
<div class="section">
<h2>6. Intellectual Property</h2>
        
<h3>6.1 Service Ownership</h3>
<p>The Service, including its code, design, features, and branding, is owned by FinSim and 
protected by copyright and intellectual property laws.</p>
        
<h3>6.2 Your Content</h3>
<ul>
<li>You retain ownership of your financial data</li>
<li>You grant us a worldwide, royalty-free, non-exclusive license to use, host, store, copy, modify, and display your data solely for the purpose of operating and improving the Service.</li>
<li>You can export and delete your data at any time</li>
                
</ul>
        
<h3>6.3 Usage Rights</h3>
<ul>
<li>Reports generated by FinSim are for your personal use</li>
<li>You may share your reports for personal purposes</li>
<li>Commercial use requires written permission</li>
</ul>
</div>
    """, unsafe_allow_html=True)

    # Rate Limits
    st.markdown("""
<div class="section">
<h2>7. Rate Limits & Fair Use</h2>
        
<h3>7.1 Free User Limits</h3>
<ul>
<li><strong>Simulations:</strong> 10 per month</li>
<li><strong>Exports:</strong> Unlimited (for your simulations)</li>
<li><strong>Data Storage:</strong> Unlimited (reasonable use)</li>
</ul>
        
<h3>7.2 Fair Use Policy</h3>
<p>We reserve the right to throttle or suspend accounts that:</p>
<ul>
<li>Exceed rate limits repeatedly</li>
<li>Generate excessive server load</li>
<li>Abuse the Service</li>
</ul>
</div>
    """, unsafe_allow_html=True)

    # Disclaimer of Warranties
    st.markdown("""
<div class="section">
<h2>8. Disclaimer of Warranties</h2>
        
<p><strong>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND.</strong></p>
        
<h3>We do NOT warrant that:</h3>
<ul>
<li>The Service will be uninterrupted or error-free</li>
<li>Defects will be corrected</li>
<li>The Service is free of viruses or harmful components</li>
<li>Results will be accurate, complete, or reliable</li>
<li>The Service will meet your specific needs</li>
</ul>
        
<h3>You acknowledge that:</h3>
<ul>
<li>Simulations are estimates based on assumptions</li>
<li>Data loss may occur despite our best efforts</li>
<li>Service interruptions may happen</li>
<li>You should back up your exported data</li>
</ul>
</div>
    """, unsafe_allow_html=True)

    # Limitation of Liability
    st.markdown("""
<div class="section">
<h2>9. Limitation of Liability</h2>
        
<p><strong>TO THE MAXIMUM EXTENT PERMITTED BY LAW:</strong></p>
        
<h3>We are NOT liable for:</h3>
<ul>
<li>Financial losses from decisions based on FinSim projections</li>
<li>Missed investment opportunities</li>
<li>Incorrect calculations or data errors</li>
<li>Data loss or corruption</li>
<li>Service downtime or interruptions</li>
<li>Unauthorized access to your account</li>
<li>Any indirect, incidental, or consequential damages</li>
<li>Data Backup: You are responsible for backing up your data and information that resides on or is used with the Service.</li>
</ul>
        
<h3>Maximum Liability:</h3>
<p>Our total liability to you for any claim shall not exceed $100 USD or the amount you 
paid us in the past 12 months (whichever is greater). Since FinSim is free, this is 
effectively $100.</p>
</div>
    """, unsafe_allow_html=True)

    # Indemnification
    st.markdown("""
<div class="section">
<h2>10. Indemnification</h2>
<p>You agree to indemnify and hold harmless FinSim, its operators, and affiliates from any 
claims, damages, losses, or expenses (including legal fees) arising from:</p>
<ul>
<li>Your use of the Service</li>
<li>Your violation of these Terms</li>
<li>Your violation of any third-party rights</li>
<li>Your financial decisions</li>
</ul>
</div>
    """, unsafe_allow_html=True)

    # Data & Privacy
    st.markdown("""
<div class="section">
<h2>11. Privacy & Data</h2>
<p>Your use of the Service is also governed by our <a href="?page=privacy">Privacy Policy</a>. 
Key points:</p>
<ul>
<li>We collect only necessary data</li>
<li>You can export or delete your data anytime</li>
<li>See the full Privacy Policy for details</li>
</ul>
</div>
    """, unsafe_allow_html=True)

    # Changes to Terms
    st.markdown("""
<div class="section">
<h2>12. Changes to Terms</h2>
<p>We may modify these Terms at any time. Changes will be effective when posted, with the 
"Last Updated" date revised. Material changes will be communicated via:</p>
<ul>
<li>Email notification</li>
<li>In-app notification</li>
<li>Notice on the homepage</li>
</ul>
<p>Continued use after changes constitutes acceptance. If you disagree, stop using the Service.</p>
</div>
    """, unsafe_allow_html=True)

    # Governing Law
    st.markdown("""
<div class="section">
<h2>13.1 Governing Law</h2>
<p>These Terms shall be governed by and construed in accordance with the laws of England and Wales, without regard to its conflict of law principles.</p>

<h2>13.2 Venue</h2>
<p>You agree that any legal action or proceeding arising under these Terms will be brought exclusively in the courts located in London, England, and you hereby consent to the personal jurisdiction and venue therein.</p>
                
            
</div>
    """, unsafe_allow_html=True)

    # Mandatory Arbitration
    st.markdown("""
<div class="section">
<h2>14. Mandatory Arbitration and Class Action Waiver</h2>
        
<h3>14.1 Agreement to Arbitrate</h3>
<p>Any and all disputes, claims, or controversies arising out of or relating to these Terms or your use of the Service shall be determined exclusively by binding arbitration in London, England, before one arbitrator. The arbitration shall be administered by the London Court of International Arbitration (LCIA) in accordance with its rules. Judgment on the award rendered by the arbitrator may be entered in any court having jurisdiction thereof.</p>
        
<h3>14.2 Class Action Waiver</h3>
<p>You agree that all claims must be brought in your individual capacity, and not as a plaintiff or class member in any purported class, collective, coordinated, or representative proceeding.</p>
        
<div class="warning-box">
<strong>⚠️ IMPORTANT:</strong> BY ENTERING INTO THESE TERMS, YOU AND FINSIM ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION.
</div>
</div>
    """, unsafe_allow_html=True)

    # Severability
    st.markdown("""
<div class="section">
<h2>15. Severability</h2>
<p>If any provision of these Terms is found to be invalid or unenforceable, the remaining 
provisions will continue in full force and effect.</p>
</div>
    """, unsafe_allow_html=True)

    # Contact
    st.markdown("""
<div class="section">
<h2>16. Contact</h2>
<p>Questions about these Terms?</p>
<ul>
<li><strong>Contact Form:</strong> <a href="?page=contact">Contact Page</a></li>
</ul>
</div>
    """, unsafe_allow_html=True)
# <li><strong>Email:</strong> legal@finsim.com (placeholder - update with real contact)</li>

    # Acknowledgment
    st.markdown("""
<div class="section">
<h2>17. Acknowledgment</h2>
<p>BY USING FINSIM, YOU ACKNOWLEDGE THAT:</p>
<ul>
<li>✅ You have read and understood these Terms</li>
<li>✅ You agree to be bound by these Terms</li>
<li>✅ FinSim is an educational tool, not financial advice</li>
<li>✅ You are responsible for your own financial decisions</li>
<li>✅ You will consult qualified professionals before making major financial decisions</li>
</ul>
</div>
    """, unsafe_allow_html=True)

    # Footer
    st.markdown("---")
    
    # Back to home button
    if st.button("← Back to Home", key="terms_back", use_container_width=True):
        st.query_params.clear()
        st.rerun()
    
    st.markdown("<br>", unsafe_allow_html=True)
    
    # Footer links as buttons
    footer_col1, footer_col2, footer_col3 = st.columns(3)
    with footer_col1:
        if st.button("About", key="terms_to_about", use_container_width=True):
            st.query_params['page'] = 'about'
            st.rerun()
    with footer_col2:
        if st.button("Privacy Policy", key="terms_to_privacy", use_container_width=True):
            st.query_params['page'] = 'privacy'
            st.rerun()
    with footer_col3:
        if st.button("Contact", key="terms_to_contact", use_container_width=True):
            st.query_params['page'] = 'contact'
            st.rerun()
